// flow-typed signature: 6c035862d995d489f62746098d6930e2
// flow-typed version: <<STUB>>/eslint-config-zacanger_v3.4.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-zacanger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-zacanger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-zacanger/helpers' {
  declare module.exports: any;
}

declare module 'eslint-config-zacanger/rules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-zacanger/helpers.js' {
  declare module.exports: $Exports<'eslint-config-zacanger/helpers'>;
}
declare module 'eslint-config-zacanger/index' {
  declare module.exports: $Exports<'eslint-config-zacanger'>;
}
declare module 'eslint-config-zacanger/index.js' {
  declare module.exports: $Exports<'eslint-config-zacanger'>;
}
declare module 'eslint-config-zacanger/rules.js' {
  declare module.exports: $Exports<'eslint-config-zacanger/rules'>;
}
