// flow-typed signature: dada4d5ebabd513024b234a2d478348f
// flow-typed version: <<STUB>>/opencollective_v^1.0.3/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opencollective'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opencollective' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opencollective/dist/bin/opencollective' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/collective' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/donate-help' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/donate' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/email' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/help' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/open' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/postinstall-help' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/postinstall-plain' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/postinstall-rich' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/postinstall' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/setup' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/slack' {
  declare module.exports: any;
}

declare module 'opencollective/dist/commands/twitter' {
  declare module.exports: any;
}

declare module 'opencollective/dist/lib/fetchData' {
  declare module.exports: any;
}

declare module 'opencollective/dist/lib/print' {
  declare module.exports: any;
}

declare module 'opencollective/dist/lib/utils' {
  declare module.exports: any;
}

declare module 'opencollective/src/bin/opencollective' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/collective' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/donate-help' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/donate' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/email' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/help' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/open' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/postinstall-help' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/postinstall-plain' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/postinstall-rich' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/postinstall' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/setup' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/slack' {
  declare module.exports: any;
}

declare module 'opencollective/src/commands/twitter' {
  declare module.exports: any;
}

declare module 'opencollective/src/lib/fetchData' {
  declare module.exports: any;
}

declare module 'opencollective/src/lib/print' {
  declare module.exports: any;
}

declare module 'opencollective/src/lib/utils' {
  declare module.exports: any;
}

declare module 'opencollective/test/postinstall.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opencollective/dist/bin/opencollective.js' {
  declare module.exports: $Exports<'opencollective/dist/bin/opencollective'>;
}
declare module 'opencollective/dist/commands/collective.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/collective'>;
}
declare module 'opencollective/dist/commands/donate-help.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/donate-help'>;
}
declare module 'opencollective/dist/commands/donate.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/donate'>;
}
declare module 'opencollective/dist/commands/email.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/email'>;
}
declare module 'opencollective/dist/commands/help.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/help'>;
}
declare module 'opencollective/dist/commands/open.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/open'>;
}
declare module 'opencollective/dist/commands/postinstall-help.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/postinstall-help'>;
}
declare module 'opencollective/dist/commands/postinstall-plain.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/postinstall-plain'>;
}
declare module 'opencollective/dist/commands/postinstall-rich.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/postinstall-rich'>;
}
declare module 'opencollective/dist/commands/postinstall.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/postinstall'>;
}
declare module 'opencollective/dist/commands/setup.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/setup'>;
}
declare module 'opencollective/dist/commands/slack.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/slack'>;
}
declare module 'opencollective/dist/commands/twitter.js' {
  declare module.exports: $Exports<'opencollective/dist/commands/twitter'>;
}
declare module 'opencollective/dist/lib/fetchData.js' {
  declare module.exports: $Exports<'opencollective/dist/lib/fetchData'>;
}
declare module 'opencollective/dist/lib/print.js' {
  declare module.exports: $Exports<'opencollective/dist/lib/print'>;
}
declare module 'opencollective/dist/lib/utils.js' {
  declare module.exports: $Exports<'opencollective/dist/lib/utils'>;
}
declare module 'opencollective/src/bin/opencollective.js' {
  declare module.exports: $Exports<'opencollective/src/bin/opencollective'>;
}
declare module 'opencollective/src/commands/collective.js' {
  declare module.exports: $Exports<'opencollective/src/commands/collective'>;
}
declare module 'opencollective/src/commands/donate-help.js' {
  declare module.exports: $Exports<'opencollective/src/commands/donate-help'>;
}
declare module 'opencollective/src/commands/donate.js' {
  declare module.exports: $Exports<'opencollective/src/commands/donate'>;
}
declare module 'opencollective/src/commands/email.js' {
  declare module.exports: $Exports<'opencollective/src/commands/email'>;
}
declare module 'opencollective/src/commands/help.js' {
  declare module.exports: $Exports<'opencollective/src/commands/help'>;
}
declare module 'opencollective/src/commands/open.js' {
  declare module.exports: $Exports<'opencollective/src/commands/open'>;
}
declare module 'opencollective/src/commands/postinstall-help.js' {
  declare module.exports: $Exports<'opencollective/src/commands/postinstall-help'>;
}
declare module 'opencollective/src/commands/postinstall-plain.js' {
  declare module.exports: $Exports<'opencollective/src/commands/postinstall-plain'>;
}
declare module 'opencollective/src/commands/postinstall-rich.js' {
  declare module.exports: $Exports<'opencollective/src/commands/postinstall-rich'>;
}
declare module 'opencollective/src/commands/postinstall.js' {
  declare module.exports: $Exports<'opencollective/src/commands/postinstall'>;
}
declare module 'opencollective/src/commands/setup.js' {
  declare module.exports: $Exports<'opencollective/src/commands/setup'>;
}
declare module 'opencollective/src/commands/slack.js' {
  declare module.exports: $Exports<'opencollective/src/commands/slack'>;
}
declare module 'opencollective/src/commands/twitter.js' {
  declare module.exports: $Exports<'opencollective/src/commands/twitter'>;
}
declare module 'opencollective/src/lib/fetchData.js' {
  declare module.exports: $Exports<'opencollective/src/lib/fetchData'>;
}
declare module 'opencollective/src/lib/print.js' {
  declare module.exports: $Exports<'opencollective/src/lib/print'>;
}
declare module 'opencollective/src/lib/utils.js' {
  declare module.exports: $Exports<'opencollective/src/lib/utils'>;
}
declare module 'opencollective/test/postinstall.test.js' {
  declare module.exports: $Exports<'opencollective/test/postinstall.test'>;
}
