// flow-typed signature: abccb305a6b03b339143fd7abc0abdf6
// flow-typed version: <<STUB>>/opencollective-postinstall_v2.0.2/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opencollective-postinstall'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opencollective-postinstall' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opencollective-postinstall/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opencollective-postinstall/index' {
  declare module.exports: $Exports<'opencollective-postinstall'>;
}
declare module 'opencollective-postinstall/index.js' {
  declare module.exports: $Exports<'opencollective-postinstall'>;
}
declare module 'opencollective-postinstall/index.test.js' {
  declare module.exports: $Exports<'opencollective-postinstall/index.test'>;
}
