// flow-typed signature: 5884f65a5fa7e1b80205ca846380b48d
// flow-typed version: <<STUB>>/sortpack_v1.1.5/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sortpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sortpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sortpack/lib/index' {
  declare module.exports: any;
}

declare module 'sortpack/lib/order' {
  declare module.exports: any;
}

declare module 'sortpack/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sortpack/index' {
  declare module.exports: $Exports<'sortpack'>;
}
declare module 'sortpack/index.js' {
  declare module.exports: $Exports<'sortpack'>;
}
declare module 'sortpack/lib/index.js' {
  declare module.exports: $Exports<'sortpack/lib/index'>;
}
declare module 'sortpack/lib/order.js' {
  declare module.exports: $Exports<'sortpack/lib/order'>;
}
declare module 'sortpack/lib/util.js' {
  declare module.exports: $Exports<'sortpack/lib/util'>;
}
